### ISSUE TITLE
Arduino_create() don't open serial port

### ISSUE THREAD

**Issue by Maizeninha** [YAL-GameMaker/Arduino#1]
I pick the test code in your repo and it still didn't working

the code:

// this is copy-pasted from the original example
ard = arduino_create("COM20", 38400)
data = ard < 0 ? "Failed to open a connection" : ""
res = string(ard)

**Comment by YellowAfterlife** [comment]
If you came for advice, you came to a wrong place - I re-compiled the existing code for x64, added a few functions (that do the same as old functions, but for non-string data types), and had someone confirm that their old code still works with the new extension. That's it. I don't own a single Arduino
